export const PEOPLE = [
	'Benedict',
	'Chrissy',
	'Derrick',
	'Glenda',
	'Jaclyn',
	'Jake',
	'Jamie',
	'Kiersten',
	'Marc',
	'Nathan',
	'Nickall',
	'Robin',
	'Ryan',
	'Sophie',
	'Stephanie',
	'Theodore',
];

export const TEAMS = {
	'': '', // for current year
	ANA: 'Anaheim Ducks',
	BOS: 'Boston Bruins',
	CAR: 'Carolina Hurricanes',
	CHI: 'Chicago Blackhawks',
	COL: 'Colorado Avalanche',
	DAL: 'Dallas Stars',
	DET: 'Detroit Red Wings',
	EDM: 'Edmonton Oilers',
	FLA: 'Florida Panthers',
	LAK: 'Los Angeles Kings',
	LOCKOUT: 'LOCKOUT',
	NJD: 'New Jersey Devils',
	PIT: 'Pittsburgh Penguins',
	STL: 'St. Louis Blues',
	TBL: 'Tampa Bay Lightning',
	VGK: 'Vegas Golden Knights',
	WAS: 'Washington Capitals',
	WSH: 'Washington Capitals', // NHL API uses WSH instead of WAS
};
