export const PEOPLE = [
    'Benedict',
    'Chrissy',
    'Derrick',
    'Glenda',
    'Jaclyn',
    'Jake',
    'Jamie',
    'Kiersten',
    'Marc',
    'Nathan',
    'Nickall',
    'Robin',
    'Ryan',
    'Sophie',
    'Stephanie',
    'Theodore'
];

export const TEAMS = {
    '': '', // for current year
    'ANA': 'Anaheim Ducks',
    'BOS': 'Boston Bruins',
    'CAR': 'Carolina Hurricanes',
    'CHI': 'Chicago Blackhawks',
    'COL': 'Colorado Avalanche',
    'DAL': 'Dallas Stars',
    'DET': 'Detroit Red Wings',
    'FLA': 'Florida Panthers',
    'LAK': 'Los Angeles Kings',
    'LOCKOUT': 'LOCKOUT',
    'NJD': 'New Jersey Devils',
    'PIT': 'Pittsburgh Penguins',
    'STL': 'St. Louis Blues',
    'TBL': 'Tampa Bay Lightning',
    'VGK': 'Vegas Golden Knights',
    'WAS': 'Washington Capitals',
};

export const DATA = [
    { year: 1996, link: false, poolWinners: 'Derrick', poolLosers: '', cupWinner: 'COL'},
    { year: 1997, link: true, poolWinners: 'Jaclyn', poolLosers: 'Marc', cupWinner: 'DET'},
    { year: 1998, link: true, poolWinners: 'Jaclyn', poolLosers: 'Chrissy', cupWinner: 'DET'},
    { year: 1999, link: true, poolWinners: 'Derrick', poolLosers: 'Stephanie', cupWinner: 'DAL'},
    { year: 2000, link: true, poolWinners: 'Derrick', poolLosers: 'Chrissy', cupWinner: 'NJD'},
    { year: 2001, link: true, poolWinners: 'Chrissy', poolLosers: 'Derrick', cupWinner: 'COL'},
    { year: 2002, link: true, poolWinners: 'Chrissy', poolLosers: 'Stephanie', cupWinner: 'DET'},
    { year: 2003, link: true, poolWinners: 'Marc', poolLosers: 'Derrick', cupWinner: 'NJD'},
    { year: 2004, link: true, poolWinners: 'Derrick', poolLosers: 'Stephanie', cupWinner: 'TBL'},
    { year: 2005, link: false, poolWinners: '-', poolLosers: '-', cupWinner: 'LOCKOUT'},
    { year: 2006, link: true, poolWinners: 'Derrick', poolLosers: 'Jaclyn', cupWinner: 'CAR'},
    { year: 2007, link: true, poolWinners: 'Marc*', poolLosers: 'Chrissy', cupWinner: 'ANA'},
    { year: 2008, link: true, poolWinners: 'Chrissy', poolLosers: ['Derrick', 'Stephanie'], cupWinner: 'DET'},
    { year: 2009, link: true, poolWinners: 'Marc', poolLosers: 'Nickall', cupWinner: 'PIT'},
    { year: 2010, link: true, poolWinners: 'Jaclyn', poolLosers: 'Derrick', cupWinner: 'CHI'},
    { year: 2011, link: true, poolWinners: 'Marc', poolLosers: 'Jaclyn', cupWinner: 'BOS'},
    { year: 2012, link: true, poolWinners: 'Nathan**', poolLosers: 'Stephanie', cupWinner: 'LAK'},
    { year: 2013, link: false, poolWinners: 'Derrick', poolLosers: 'Ryan', cupWinner: 'CHI'},
    { year: 2014, link: true, poolWinners: 'Nathan', poolLosers: 'Nickall', cupWinner: 'LAK'},
    { year: 2015, link: true, poolWinners: 'Nathan', poolLosers: 'Glenda', cupWinner: 'CHI'},
    { year: 2016, link: true, poolWinners: 'Stephanie', poolLosers: 'Derrick', cupWinner: 'PIT'},
    { year: 2017, link: true, poolWinners: 'Glenda', poolLosers: ['Jake', 'Nickall'], cupWinner: 'PIT'},
    { year: 2018, link: true, poolWinners: 'Ryan', poolLosers: 'Robin', cupWinner: 'WAS'},
    { year: 2019, link: true, poolWinners: 'Nathan', poolLosers: 'Marc', cupWinner: 'STL'},
    { year: 2020, link: true, poolWinners: 'Nathan', poolLosers: 'Robin', cupWinner: 'TBL'},
    { year: 2021, link: true, poolWinners: 'Stephanie', poolLosers: ['Kiersten', 'Robin'], cupWinner: 'TBL'},
    { year: 2022, link: true, poolWinners: 'Stephanie', poolLosers: 'Glenda', cupWinner: 'COL'},
    { year: 2023, link: true, poolWinners: 'Nathan', poolLosers: 'Jake', cupWinner: 'VGK'},
    { year: 2024, link: true, poolWinners: 'Glenda', poolLosers: 'Jake', cupWinner: 'FLA'}
];
